---
strategy: webhook
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: ''
polling_headers: ''
id: 84292
custom_fields:
- keyname: bio
  name: About This Plugin
  field_type: author_bio
  description: TRMNL HomeAssistant Smart Home Weather Station Integration
  github_url: https://github.com/TilmanGriesel/ha_trmnl_weather_station
  learn_more_url: https://github.com/TilmanGriesel/ha_trmnl_weather_station
  email_address: griesel@me.com
name: Home Assistant Weather Station [DEV]
refresh_interval: 15
