name: HACS Action
on:
  # Automatic triggers commented out - now manual only
  push:
  pull_request:
  schedule:
   - cron: "0 0 * * *"

  # Manual trigger only
  workflow_dispatch:

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
